import { useState, useEffect, useCallback } from 'react';
import { motion } from 'framer-motion';
import {
  Phone, PhoneIncoming, PhoneOutgoing, Clock, Star, HardDrive,
  Mic, Radio, Zap, TrendingUp
} from 'lucide-react';
import { useRecordingsStore } from '../stores/recordingsStore';
import { useAppStore } from '../stores/appStore';
import { formatDistanceToNow } from 'date-fns';
import { v4 as uuidv4 } from 'uuid';
import type { Recording } from '../types';

const simulatedTranscripts = [
  "Hey, I'm calling about the meeting tomorrow. Can we reschedule to 3 PM? I have a conflict with the morning slot. Also, please bring the updated proposal — the client wants to review the pricing section before we finalize.",
  "Hi, this is regarding your application. We'd like to invite you for a second round interview. It would be a panel interview with three team leads. Can you come in next Wednesday at 10 AM? Please prepare a brief presentation about your most recent project.",
  "Just checking in about the delivery. The package should arrive by Thursday. The tracking number has been sent to your email. If there are any issues with the shipment, call our support line directly and reference order number UC-2026-7734.",
];

const simulatedContacts = [
  { name: 'Elena Vasquez', phone: '+1 (555) 901-2345' },
  { name: 'James Mitchell', phone: '+1 (555) 234-5678' },
  { name: undefined, phone: '+1 (555) 456-7890' },
];

export function Dashboard() {
  const { recordings } = useRecordingsStore();
  const { isRecording, setIsRecording, setCurrentRecordingId, setSelectedRecordingId, setActiveTab } = useAppStore();
  const addRecording = useRecordingsStore(s => s.addRecording);
  const [simProgress, setSimProgress] = useState(0);
  const [simDuration, setSimDuration] = useState(0);

  const totalDuration = recordings.reduce((s, r) => s + (r.durationSeconds || 0), 0);
  const favorites = recordings.filter(r => r.isFavorite).length;
  const incoming = recordings.filter(r => r.direction === 'incoming').length;
  const outgoing = recordings.filter(r => r.direction === 'outgoing').length;
  const recentRecordings = recordings.slice(0, 5);

  useEffect(() => {
    if (!isRecording) return;
    const iv = setInterval(() => {
      setSimDuration(p => p + 1);
      setSimProgress(p => Math.min(p + 2, 100));
    }, 1000);
    return () => clearInterval(iv);
  }, [isRecording]);

  const startSimulatedCall = useCallback(async () => {
    if (isRecording) return;
    setIsRecording(true);
    setSimProgress(0);
    setSimDuration(0);

    const contactIdx = Math.floor(Math.random() * simulatedContacts.length);
    const transcriptIdx = Math.floor(Math.random() * simulatedTranscripts.length);
    const contact = simulatedContacts[contactIdx];
    const direction: Recording['direction'] = Math.random() > 0.5 ? 'incoming' : 'outgoing';
    const id = uuidv4();
    setCurrentRecordingId(id);

    // Simulate a 8-15 second "call"
    const callDuration = 8000 + Math.floor(Math.random() * 7000);
    setTimeout(async () => {
      const startTime = new Date(Date.now() - callDuration);
      const endTime = new Date();
      const durationSeconds = Math.round(callDuration / 1000);

      const rec: Recording = {
        id,
        callId: `CALL-${Date.now()}`,
        phoneNumber: contact.phone,
        contactName: contact.name,
        direction,
        startTime,
        endTime,
        durationSeconds,
        audioFilePath: `/recordings/sim_${id}.opus`,
        micFallbackPath: `/recordings/mic_${id}.opus`,
        transcript: simulatedTranscripts[transcriptIdx],
        tags: ['simulated'],
        isFavorite: false,
        sourceMethod: 'both',
        summary: 'Simulated call recording generated by UltraCall Vault demo engine.',
      };

      await addRecording(rec);
      setIsRecording(false);
      setCurrentRecordingId(null);
      setSimProgress(100);
    }, callDuration);
  }, [isRecording, addRecording, setIsRecording, setCurrentRecordingId]);

  const formatDuration = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = secs % 60;
    if (h > 0) return `${h}h ${m}m`;
    if (m > 0) return `${m}m ${s}s`;
    return `${s}s`;
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-orbitron text-xl font-bold neon-text">UltraCall Vault</h1>
          <p className="text-xs text-vault-muted mt-0.5">Recording Engine Active</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-vault-success recording-dot" />
          <span className="text-xs text-vault-success font-medium">Online</span>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 gap-3">
        <StatCard icon={<Phone className="w-4 h-4" />} label="Total Calls" value={recordings.length} color="cyan" />
        <StatCard icon={<Clock className="w-4 h-4" />} label="Total Duration" value={formatDuration(totalDuration)} color="purple" />
        <StatCard icon={<Star className="w-4 h-4" />} label="Favorites" value={favorites} color="warning" />
        <StatCard icon={<HardDrive className="w-4 h-4" />} label="Storage" value={`${(recordings.length * 2.4).toFixed(1)} MB`} color="cyan" />
      </div>

      {/* Call Direction Split */}
      <div className="glass-card p-4">
        <h3 className="font-orbitron text-xs text-vault-muted mb-3">CALL DIRECTION</h3>
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="h-2 rounded-full bg-vault-glass overflow-hidden flex">
              <div
                className="h-full bg-vault-cyan rounded-l-full transition-all"
                style={{ width: recordings.length ? `${(incoming / recordings.length) * 100}%` : '50%' }}
              />
              <div
                className="h-full bg-vault-purple rounded-r-full transition-all"
                style={{ width: recordings.length ? `${(outgoing / recordings.length) * 100}%` : '50%' }}
              />
            </div>
          </div>
          <div className="flex gap-4 text-xs">
            <span className="flex items-center gap-1"><PhoneIncoming className="w-3 h-3 text-vault-cyan" /> {incoming}</span>
            <span className="flex items-center gap-1"><PhoneOutgoing className="w-3 h-3 text-vault-purple" /> {outgoing}</span>
          </div>
        </div>
      </div>

      {/* Simulate Call Button */}
      <motion.button
        onClick={startSimulatedCall}
        disabled={isRecording}
        className={`w-full p-5 rounded-2xl border-2 transition-all ${
          isRecording
            ? 'border-vault-danger/50 bg-vault-danger/10'
            : 'border-vault-cyan/30 bg-vault-cyan/5 hover:border-vault-cyan/60 hover:bg-vault-cyan/10'
        }`}
        whileTap={isRecording ? {} : { scale: 0.98 }}
      >
        {isRecording ? (
          <div className="space-y-3">
            <div className="flex items-center justify-center gap-3">
              <div className="w-3 h-3 rounded-full bg-vault-danger recording-dot" />
              <span className="font-orbitron text-sm text-vault-danger font-bold">RECORDING IN PROGRESS</span>
            </div>
            <div className="flex justify-center gap-1">
              {Array.from({ length: 12 }).map((_, i) => (
                <motion.div
                  key={i}
                  className="w-1 bg-vault-cyan rounded-full"
                  animate={{ height: [4, 8 + Math.random() * 16, 4] }}
                  transition={{ duration: 0.5 + Math.random() * 0.5, repeat: Infinity, delay: i * 0.05 }}
                />
              ))}
            </div>
            <div className="flex items-center justify-between text-xs text-vault-muted">
              <span className="flex items-center gap-1"><Mic className="w-3 h-3" /> MIC Active</span>
              <span className="font-orbitron text-vault-cyan">{simDuration}s</span>
              <span className="flex items-center gap-1"><Radio className="w-3 h-3" /> SYS Active</span>
            </div>
            <div className="h-1 rounded-full bg-vault-glass overflow-hidden">
              <motion.div
                className="h-full rounded-full bg-gradient-to-r from-vault-cyan to-vault-purple"
                animate={{ width: `${simProgress}%` }}
              />
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-vault-cyan/20 to-vault-purple/20 flex items-center justify-center">
              <Zap className="w-6 h-6 text-vault-cyan" />
            </div>
            <div className="text-left">
              <p className="font-orbitron text-sm font-bold text-white">Simulate Call</p>
              <p className="text-xs text-vault-muted">Tap to trigger a demo recording</p>
            </div>
          </div>
        )}
      </motion.button>

      {/* Recent Recordings */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-orbitron text-xs text-vault-muted">RECENT RECORDINGS</h3>
          <button
            onClick={() => setActiveTab('recordings')}
            className="text-xs text-vault-cyan hover:underline flex items-center gap-1"
          >
            View All <TrendingUp className="w-3 h-3" />
          </button>
        </div>
        <div className="space-y-2">
          {recentRecordings.length === 0 ? (
            <div className="glass-card p-8 text-center">
              <Phone className="w-8 h-8 mx-auto text-vault-muted mb-2" />
              <p className="text-sm text-vault-muted">No recordings yet</p>
              <p className="text-xs text-vault-muted/60">Simulate a call to get started</p>
            </div>
          ) : (
            recentRecordings.map((rec, idx) => (
              <motion.button
                key={rec.id}
                onClick={() => {
                  setSelectedRecordingId(rec.id);
                  setActiveTab('recordings');
                }}
                className="w-full glass-card p-3 flex items-center gap-3 hover:border-vault-cyan/30 transition-colors text-left"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
              >
                <div className={`w-9 h-9 rounded-lg flex items-center justify-center ${
                  rec.direction === 'incoming' ? 'bg-vault-cyan/10' : 'bg-vault-purple/10'
                }`}>
                  {rec.direction === 'incoming'
                    ? <PhoneIncoming className="w-4 h-4 text-vault-cyan" />
                    : <PhoneOutgoing className="w-4 h-4 text-vault-purple" />
                  }
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-white truncate">
                    {rec.contactName || rec.phoneNumber}
                  </p>
                  <p className="text-xs text-vault-muted">
                    {formatDistanceToNow(new Date(rec.startTime), { addSuffix: true })}
                    {' · '}
                    {formatDuration(rec.durationSeconds || 0)}
                  </p>
                </div>
                {rec.isFavorite && <Star className="w-4 h-4 text-vault-warning fill-vault-warning" />}
              </motion.button>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, color }: { icon: React.ReactNode; label: string; value: string | number; color: string }) {
  const colors: Record<string, string> = {
    cyan: 'text-vault-cyan bg-vault-cyan/10 border-vault-cyan/20',
    purple: 'text-vault-purple bg-vault-purple/10 border-vault-purple/20',
    warning: 'text-vault-warning bg-vault-warning/10 border-vault-warning/20',
  };
  return (
    <div className="glass-card p-4">
      <div className={`w-8 h-8 rounded-lg flex items-center justify-center mb-2 ${colors[color]}`}>
        <span className={color === 'cyan' ? 'text-vault-cyan' : color === 'purple' ? 'text-vault-purple' : 'text-vault-warning'}>
          {icon}
        </span>
      </div>
      <p className="font-orbitron text-lg font-bold text-white">{value}</p>
      <p className="text-xs text-vault-muted">{label}</p>
    </div>
  );
}
